#!/bin/bash
#
#   Unit: hidelist
#   Description:
#       Hides all modules from a specified list. Wildcards are supported.
#
#   Author:         Brian Vanderwende
#   Last Revised:   10:57, 21 Aug 2025
#

#
##  UNIT DEPENDENCIES
#

. $POSTPROCESS_UNIT_DIR/hide-module.helper

#
##  USER INPUT
#

hide_list=" */*/mvapich/* */*/vasp/* */*/intel-mpi/* */*/mpich/* */cuda/12.8* */ucx/*-debug* */visit/*-old* "

#
##  BEGIN HIDDEN MODULE FILE GENERATION
#

for hl in $hide_list; do
    tsecho "Looking for modules to hide in $MOD_DEPLOYMENT/$hl" 1
    hide_mods="$(ls -1 --color=never $MOD_DEPLOYMENT/$hl 2> /dev/null || true)"

    for hm in $hide_mods; do
        hide_module $hm
    done
done
